version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout # GitHubからCircleCIの環境にソースコードをコピー
      - run: sudo composer self-update --1 # PHP関連パッケージのインストールのエラー回避
      - run: composer install -n --prefer-dist # PHP関連パッケージのインストール
      - run: npm ci # JavaScriptの各種パッケージのインストール
      - run: npm run dev # JavaScriptのトランスパイル
      - run:
        name: php test #テストの実行
        command: vendor/bin/phpunit